### PR TITLE
Update project to use hyper = ^0.11

### PR DESCRIPTION
**Pull request by XX**
Hi. I rewrote the code to use the latest version of the hyper. Please check that everything is done correctly.

### CODE REVIEW

**Comment by marad** [comment]
@XX Hi, thanks for your contribution! 
I see that there are a lot of changes. Some of them seem to break backward compatibility. Is this necessary?

**Comment by tistatos** [comment]
What is the status of this pull request? Perhaps it would be possible to avoid the breaking the backwards compability by still allow user to use either old method or `Service` trait?

I'm currently using this fork in my project. And I've also started modifying it to be able to handle responses via futures (enabling me to use the hyper `send_file` example). So it would be nice to get this merged

**Comment by marad** [comment]
@tistatos Not sure, @XX didn't respond at all. Maybe breaking the backwards compatibility is not an issue if I update the version accurately?

**Comment by jeffvandyke** [comment]
Hi there! I'm still pretty new to Rust, and I really like what this project is trying to do, so as soon as I figure out how, I can test some of these examples to make sure they still work. Hyper seems crazy popular, so it would be nice if this worked with the latest `0.11.27` version.

There is the obvious backwards compatibility break of the handler function signatures, but if hyper's going that direction, then it seems inevitable. Incrementing the version number as the Pull Request does follows [semver](https://semver.org/) semantics and is the right way to deal with this kind of backward compatibility break, so if everything works, I'm a fan of this getting merged as well!

**Comment by marad** [comment]
Hmm, I guess you're right @jeffvandyke. I'll merge this and publish the new version.

**Pull request merged**
