### PR TITLE
Hyper 0.12

### PR DESCRIPTION
**Pull request by mersinvald**
Hello, @marad!

I've ported hyper-router to `Hyper 0.12`, please look through the changes and say what do you think about these breaking changes that are necessary for the next version of hyper and if they can land into `hyper-router 0.5`

I've decided to support only the `Body` type in generic body position for `Request` and `Response` as there seems to be no way to generalize `Router` middleware abstraction over an open set of  `Request/Response` generic arguments.

### CODE REVIEW

**Comment by marad** [comment]
Hello @mersinvald, thanks for your contribution!
I'll have a look at this later today and will generate new version if everything is ok :)

**Comment by mersinvald** [comment]
Hi, @marad, do you have some comments and suggestions or everything's ok?

**Comment by mersinvald** [comment]
Okay, tried to use it in the real project, there are some caveats because of Body I'd like to get rid of.
Will try to find a way to introduce support for more types returned in Response.

**Comment by marad** [comment]
Hi @mersinvald, thanks for checking this out! I haven't had time this week and next week I'm out for holidays. I'm not sure if I can accept that before next monday. 

I'd greatly appreciate your help with testing this code till then.

**Comment by Fedcomp** [comment]
@mersinvald what caveats?

**Comment by mersinvald** [comment]
@Fedcomp basically I'd like to not to have the router accept only the `Request<Body> -> Response<Body>` but support any `T where T: Payload` as the generic argument

**Comment by marad** [comment]
@mersinvald I've spent some time yesterday moving this library to 21st century by applying 2018 fixes and, rustfmt and resolving all clippy issues. 

Are you still interested in merging this? If yes then please sort out the merge conflicts. If not - I'll probably update to hyper 0.12 this week.

Also - have you managed to sort out the caveats you were writing about earlier?

**Comment by mersinvald** [comment]
@marad no, not really, I have switched to actix-web. If you want to base your code update on my changes, I'll resolve the merge conflicts, but I have no intention to continue working on this PR.

**Comment by marad** [comment]
@mersinvald Ok, so I'll just close this PR and update this to 0.12 myself. I want to use this as an excuse to refresh my Rust knowledge a bit. Sorry it took so long to get this moving.

Even though the PR is not going to be merged I greatly appreciate your contribution. Thanks for your time :)

**Comment by mersinvald** [comment]
@marad thanks for taking your time to update the lib :)
It's crucial for hyper web development IMO, one of the few routers out there (if not the only one).

**Pull request closed without merging**
